### ISSUE TITLE
Import feeds from OPML

### ISSUE THREAD

**Issue by joethei** [joethei/obsidian-rss#1]

**Comment by NilsLeo** [comment]
Hey, first of all, thank you for creating this plugin!

I’ve been trying to find the setting for importing from OPML but haven’t had any luck. Could you guide me on how to access it?

**Comment by joethei** [comment]
The second button here
![grafik](https://github.com/user-attachments/assets/1f3a077b-816f-4400-b199-0bc729043b8c)

**Comment by NilsLeo** [comment]
Danke !!
