### ISSUE TITLE
[Feature Request] Thank You + Save `Add as a Note` in a Specific Folder

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#10]
Hello @joethei !!!!

## Thank You 

I'm so excited about this plugin since your first post on Discord :)
- i'm a heavy RSS user and if you don't mind, I'd like to suggest a few FR based on my workflow :)
- If you want, I can explain to you how I'm thinking about to use this plugin :)
- Thanks for creating this amazing plugin!!!!!

## My FR

Would be amazing if we could define an specific folder when using the command to `Add as a New Note` 

I wish you a fantastic day!

**Comment by joethei** [comment]
The default folder is currently based on the Setting in `Files & Links`, but a setting for a seperate folder is something I can add.

**Comment by FelipeRearden** [comment]
> The default folder is currently based on the Setting in `Files & Links`, but a setting for a seperate folder is something I can add.

Thank you very much !!! Would be amazing! 

I have a specific folder for each type of content (Podcasts, Articles, Books and Videos). 

In this case, I would use my Articles folder to save every note created from the feed.


---

I'm sorry for creating a bunch of FR in the same moment :)

I'm so excited that I just want to share with you my ideas 

Forgive me if was too much :)

**Comment by FelipeRearden** [comment]
Thank you very much @joethei !!!

Working perfect on Obsidian `0.12.19` version `0.5.0`
