### ISSUE TITLE
turning off tooltips breaks card display

### ISSUE THREAD

**Issue by bedginton** [joethei/obsidian-rss#106]
When I insert this css
`.rss-tooltip {
    display: none !important;
}
`
the displaying of cards in the right-column RSS view stops.  I've attached before CSS and after CSS snippet enabled.

Current version v1.0.2
(Installer version: v0.14.15)
Theme: minimal 

![Screenshot 2022-10-23 at 6 58 25 AM](https://user-images.githubusercontent.com/78746/197393721-f2a1251b-99cf-459f-b560-07ed3e4a637b.png)
![Screenshot 2022-10-23 at 6 58 45 AM](https://user-images.githubusercontent.com/78746/197393723-e4952543-5ffb-4d25-830b-c9165607420b.png)

**Comment by joethei** [comment]
This is to be expected, the snippet you have written does not target the tooltips.
I know that this is confusing, the next version of the plugin will change how all the CSS classes are named.

You should target `.rss-tooltip:hover .tooltiptext` instead.

Also, something unrelated, you should update your installer by downloading a new version from: <https://obsidian.md/download>
This is sometimes necessary as the automatic update does not update all components of Obsidian.
