### ISSUE TITLE
RSS Reader Plugin Doesn't Like A Feed I'm Trying To Add

### ISSUE THREAD

**Issue by FrankNJohnson** [joethei/obsidian-rss#109]
I looked through the open issues and don't believe this has been reported. I'm trying to add this feed - https://www.abwe.org/taxonomy/term/175/all/feed/feed.rss (if I put that feed address in Microsoft Edge, it returns the articles in the feed so as far as I can tell, there isn't a problem with the feed itself - although I could be wrong as I'm far from an expert - and I have added other feeds without any problems). But the RSS Reader plugin doesn't like it for some reason. When I try to enter it like this:

<img width="420" alt="rss-reader-plugin-ss1" src="https://user-images.githubusercontent.com/116246915/204119867-dccd5d5f-c700-465d-803c-12710780a81b.png">

I get an error message:

<img width="174" alt="rss-reader-plugin-ss2" src="https://user-images.githubusercontent.com/116246915/204119877-ea74d26d-efda-48a7-9006-84d051050463.png">

and the URL field disappears from the form where you enter the feed details:

<img width="423" alt="rss-reader-plugin-ss3" src="https://user-images.githubusercontent.com/116246915/204119884-0b0262f0-542f-4d5a-9314-7bfed1ad3261.png">

Let me know if you have any questions about my process or what I'm observing. And thanks for any help you can offer!

**Comment by joethei** [comment]
The link does not point to an RSS feed just to the same article list.

I don't see any links to an RSS feed on that site, the one that exists in the HTML just points to that site again for some reason.

**Comment by FrankNJohnson** [comment]
Okay, thanks. I meant to test it in another feed reader before posting, but forgot to do so - now I see my main feed reader (until now - thinking of replacing it with your plugin) doesn't like it either. Sorry for the "wild goose chase."
