### ISSUE TITLE
[Feature Request] Visual identification to links that have related Note

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#11]
Hello @joethei !!!!

I’d like to request a way to highlight/emphasize that a link of a feed has a note in the vault

When you have a long feed of links, it’s difficult to control/organize which links were “transformed” into a note and which ones were only read. 

An Icon ?
A different color ?

This FR is related to: #12 

Thanks for reading this :)

**Comment by joethei** [comment]
@FelipeRearden 
here is a little preview of this feature ![](https://i.joethei.space/Obsidian_VegZY21YPX.png)
(Also for tagging #9)
will be available in a few days.

**Comment by FelipeRearden** [comment]
> here is a little preview of this feature
> 
> (Also for tagging #9)
> 

Thank you very much for the preview @joethei 👀 👀 👀 👀 👀 👀 

Amazing the note icon is very beautiful and easy to identify the "noted" links !!!!

The tags are amazing too I will use everything !!!! 


> will be available in a few days.

Great !!!!!!!


---

Thanks for sharing the preview with our community!

I wish you a fantastic day!

**Comment by FelipeRearden** [comment]
Hello @joethei !!!!

Thank you very much for this new feature!!!!

Working perfect on version `0.6.2` Obsidian `0.12.19` !!!!
