### ISSUE TITLE
iOS not supported (yet)?

### ISSUE THREAD

**Issue by fjdu** [joethei/obsidian-rss#111]
I find no way to open the rss reader in my iphone, and in the command palette when I search "rss" there is no "RSS reader: open" (while this item exists in macOS).  On the other hand, when obsidian is started in iOS, it does show a message saying "Feeds updated".

**Comment by joethei** [comment]
You probably already have it open.
The command only shows if its not open already.

By default its on the right sidebar.

**Comment by fjdu** [comment]
Oh yes!  I just figure out there is also a right sidebar in the iOS Obsidian...
Thanks!
