### ISSUE TITLE
Cannot see RSS feed tab

### ISSUE THREAD

**Issue by impactfuze** [joethei/obsidian-rss#116]
Hi there,
just installed the plugin. I cannot see the list of items and have tried the solutions proposed in #66. The problem is the same as #66 as well.

here is a screenshot of my vault:

![image](https://user-images.githubusercontent.com/13859077/209954480-e8dd5a66-94b1-4cdf-83f4-65d8dd46d028.png)

I have enabled the plugin and added feeds. I tried to make a hotkey for open feed, but it did not work. I can see the feed via the command palette open feed from URL command

![image](https://user-images.githubusercontent.com/13859077/209954430-468c8e4d-2608-4635-a6e5-9084c1ee8a2c.png)

**Comment by joethei** [comment]
Scroll in the area marked or expand it, you should be able to see the RSS icon there.

![Inked209954480-e8dd5a66-94b1-4cdf-83f4-65d8dd46d028](https://user-images.githubusercontent.com/7150512/209961809-4bcbc934-9fb8-4d31-b4e8-9be43629e89d.jpg)

**Comment by impactfuze** [comment]
Thank you
