### ISSUE TITLE
[Feature Request] Filter for Feeds

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#12]
Hello @joethei !!!!!

Would be amazing if we have a way to filter the list of links into the feed.

My suggestion of filters are:
- Read
- Unread
- Links that have a Note (Noted is a good name?) -> FR #11 

Additional feature: an option in the Settings to define the standard option to the feed when opening Obsidian.

This FR is related to #11 

Thanks :)

**Comment by joethei** [comment]
While I still need to do some work on this here is a little preview: 
![preview gif](https://i.joethei.space/cbUudvO3XH.gif)

@FelipeRearden

**Comment by FelipeRearden** [comment]
> While I still need to do some work on this here is a little preview: 


Oowwwww !!!! Amazing @joethei !!!! 

Thank you very much for making time to create this video !!!!

It's a clever way to create filter feeds !!!!!!!!

I wish you good work and a fantastic day :)

**Comment by FelipeRearden** [comment]
Hello @joethei !!!

Thank you very much !!! The Filter feature is absolutely amazing!

I really like your approach because it gives freedom to create filter feeds for every possible scenario !

This is a very important feature for my workflow. Thanks again !
