### ISSUE TITLE
[Feature Request] Quick Commands to `Add as a New Note` and `Paste to Current Note`

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#15]
Hello @joethei !!!!

My suggestion is quick ways to create a note from the side panel: 

- Mouse Left Click -> open visualization content screen;
- Mouse Right Click -> add as a New Note;
- Hold Alt/option + Mouse Left Click -> Paste to the Current Note;
- Hold Alt/option + Mouse Right Click -> open in browser ;

Thanks for reading this :)

**Comment by joethei** [comment]
I have just added a context menu to articles, together with some shortcuts:
- Ctrl + right click = create new note
- Alt + right click = paste to note
- Alt + Ctrl + right click = open in browser

These shortcuts are currently hard coded until I have figured out how to best configure them.

**Comment by FelipeRearden** [comment]
> hey @FelipeRearden
> 
> I have just added a context menu to articles, together with some shortcuts:
> 
> - Ctrl + right click = create new note
> 
> - Alt + right click = paste to note
> 
> - Alt + Ctrl + right click = open in browser
> 
> 
> 

Thank you very much @joethei !!!

Working perfect on Obsidian `0.12.19` version `0.5.0`


> These shortcuts are currently hard coded until I have figured out how to best configure them.

Great ! It's amazing to already have a hotkey for each command :)


Have a great day!
