### ISSUE TITLE
Feeds from Obsidian Forum would be all marked as read when reading only one article

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#18]
I tried to subscribe some feeds from the Obsidian forum, e.g. the following one:
https://forum.obsidian.md/t/dataview-plugin-snippet-showcase/13673.rss

After reading one of such a post, all posts from this feed would be marked as read. It could be related to the fact that all articles from this feed have the same title.

**Comment by joethei** [comment]
this will be fixed in the next release.
