### ISSUE TITLE
Title variable cannot be converted correctly if used in main content of the note

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#19]
If the variable `{{title}}` is put in the front matter, this variable can be replaced correctly by using the actual article title from the feed. However, if it is put in the main content part of the template, it cannot be recognized correctly.

Another related issue I noticed is that the `{{title}}` variable represent the title of the feed article. On the other hand, one can rename the note when creating new notes based on the article. Is it possible to have another variable that denotes the title of the file/note name?

**Comment by joethei** [comment]
Do you have an non working example for the first one as I cannot reproduce this?
@wenlzhang

**Comment by wenlzhang** [comment]
For instance, with the following RSS feed and template, it does not work for me.

https://forum.obsidian.md/t/dataview-plugin-snippet-showcase/13673.rss

```
---
title: {{title}}
source: {{link}}

tags: ['']

published at: {{published}}
created at: 

---

# {{title}}

{{content}}

```

**Comment by joethei** [comment]
this will be available in the next release in a few days.
