### ISSUE TITLE
Support fixing the row of icons when scrolling the article content

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#21]
When reading/scrolling a long article, the following icons would scroll with the article content. After skimming the article, one may want to star, create new notes, etc. for this particle article. Then, one may need to scroll back to see those icons.

Therefore, it would be more convenient if those icons can be put at a fixed location of the window, e.g. the top of the window, that does not scroll with the article.

<img width="398" alt="Screenshot 2021-11-05 at 13 32 31" src="https://user-images.githubusercontent.com/44930227/140511039-5ab53a4a-c96f-4dbe-b8e1-553e88adceb9.png">

**Comment by joethei** [comment]
will be available in the next release
