### ISSUE TITLE
Support more convenient way of adding/managing feeds

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#22]
Currently, one needs to add a feed from the plugin configuration page and type the full name of a desired folder. It would
 be great if the name of an existing folder would pop up or something similar to this, such that one does not need to type the full name of the folder.

An alternative would be to supporting adding feeds from the sidebar where when can read articles. For instance, one right click a folder name and create a feed within that folder from there.

Also, it would be great if one can assign one feed to multiple folders.

**Comment by joethei** [comment]
This is at least part of #3, so I am going to close this.
Assigning one feed to multiple folders is not something I am going to do since that complicates things further from what
I already have build towards better folder support and personally I don't see a usecase here.
