### ISSUE TITLE
Support hiding read articles from the article list

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#23]
It would be great if one can hide read articles from the list. This can be done by using a command for easier control of what to be displayed in the list.

This may be related to the following request:

[[Feature Request] Filter for Feeds · Issue #12 · joethei/obsidian-rss](https://github.com/joethei/obsidian-rss/issues/12)

It would also be helpful if one can sort articles by using "From Old to New" or the default one, i.e. "From New to Old".

**Comment by joethei** [comment]
Yes, this is related to #12, you can see a preview of the functionality there.
