### ISSUE TITLE
[Feature Request]Save all Feed articles in one folder. 

### ISSUE THREAD

**Issue by bleedingsaber** [joethei/obsidian-rss#25]
I use your amazing plugin to subscribe "my Stare articles in Inoreader" RSS feed and actually all these articles I want to save locally. So I think saving all feed articles to one obsidian folder is good for archive. How about your ideas? Thanks for your amazing work!

**Comment by Quorafind** [comment]
Good idea, it will be nice to have a feature like this.

**Comment by joethei** [comment]
In the new version(0.6.4) you now have the ability to create notes from a folder by right clicking it.

**Comment by wenlzhang** [comment]
It would also be very useful if one can save all articles within higher levels of folders. For instance, `Folder A` contains `Feed A` and `Feed B`. Currently, one can save all articles within `Feed A` or `Feed B`. It would be great if one can save all articles within `Folder A` or even the highest level folder `Folders`.

Also, it would be great if one can save articles within filtered folders, e.g. `Favourites`, `Tagged`, etc.

**Comment by wenlzhang** [comment]
It can also be very useful if one can save all read/unread articles with a feed folder or higher level of folders. A use case for this would be for forum post feeds. For instance, one can mark a few interested posts within a forum post feed as unread and save all unread posts as notes.

For this to work, then there should be a way of handing the note name issue, as all forum posts would have the same name.
