### ISSUE TITLE
Support adding created tags into note content

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#26]
Now that tagging has been supported as detailed in https://github.com/joethei/obsidian-rss/issues/9, it would be great if those tags can be inserted when creating new notes.

For instance, there can be a variable called something like `{{tag}}`, and one can use such a variable in the note template.

It may also be very useful if one can specify separators for inserting multiple tags. Specifically, if a comma is specified, then the tags would be inserted in the following way: `Tags: #Tag1, #Tag2`.

**Comment by FelipeRearden** [comment]
Hello @wenlzhang  and @joethei 

Sorry for comment into your post @wenlzhang . I just wanna add that would be good to have one variation to the `{{tags}}` variable without the hashtag `#` 

- `{{#tags}}`
- `{{tags}}`

In my case, I would use this new variable in my YAML which have this syntax `tags: [tag1, tag2]`

100% agree with the {{tags:separator}} for different purposes. 


Have a great day!!!!!

**Comment by wenlzhang** [comment]
> In my case, I would use this new variable in my YAML which have this syntax `tags: [tag1, tag2]`

Indeed, this variant would also be very useful!

**Comment by FelipeRearden** [comment]
> `{{tags}}, {{#tags}}` as well as `{{tags:seperator}}, {{#tags:seperator}}`
> 
> are now available.
> 
> If you don't specify a separator `, `  will be used.

Thank you very much @joethei for the quick reply!!!!!

Working perfect on version `0.6.3` on Obsidian `0.12.19`

I tested the 4 new variables!


Thanks :)
