### ISSUE TITLE
[Feature Request] Filtered Folders > Filter -> New Filter: Feed {{feed}}

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#28]
Hello @joethei !!!!

I’d like to suggest a new filter for the powerful Filtered Folders !

Would be amazing if we could apply a filter to a specific feed inside a folder in the field below

![3](https://user-images.githubusercontent.com/85180696/142612594-a2ab4c2b-5710-472a-9489-ce2ada76975c.png)

**Example:** 

The`Folder_Name = News` have two feeds_name `WSJ` And `NYT`

Would be amazing to create a filter feed only for `NYT`

Something like that in the field `News\NYT`

--- 

Thanks for reading this ! 

Have a great day!

**Comment by joethei** [comment]
I think you might enjoy the next version of the plugin
![Demo](https://i.joethei.space/WrV1OgaexF.gif)

Currently only the menu, gonna work on the functionality next.

**Comment by FelipeRearden** [comment]
👀 👀 👀 👀 AMAZING!!!!!!!!!!   

I loved !!!!!!!!!!!

Thank you very much doing this spectacular plug-in 😀 !!!!!

**Comment by FelipeRearden** [comment]
Working perfect on version `0.9.1` Obsidian `0.12.19` 

Thank you !!!!!!
