### ISSUE TITLE
Archiving/Removing Read Articles

### ISSUE THREAD

**Issue by frvkl** [joethei/obsidian-rss#31]
Are read articles archived/removed after x days? If not, it would be great to have some setting(s) to manage this.

**Comment by joethei** [comment]
At the moment there is no removal happening, all articles will be saved forever.
I was thinking of adding a command that allows you to clean up your articles manually and a setting
to enable automatic cleanup.

**Comment by frvkl** [comment]
That would be great. Looking forward how the plugin progresses. Good Job!

**Comment by frvkl** [comment]
Perhaps an idea to make an additional setting to exclude 'favorited' articles from the archiving/removing process.

**Comment by frvkl** [comment]
I did not mean to close this ticket 😕

**Comment by joethei** [comment]
![](https://i.joethei.space/Obsidian_tiwQntu85L.png)

this is a little preview how the cleanup menu might look,
you can configure what you want to delete with this

**Comment by joethei** [comment]
in the next update(soon^tm) you will be able to open this menu with the command `Cleanup articles`, or with a button in the plugin settings.

 I am not to sure on doing automatic removal, since once you remove an item they might reappear if they are still available on the server.
