### ISSUE TITLE
'Refresh Feeds' requires restarting Obsidian to see the fetched feeds in the list

### ISSUE THREAD

**Issue by frvkl** [joethei/obsidian-rss#32]
It seems that the 'Refresh Feeds' command does fetch new articles on desktop, but the new articles do not show up in the list until Obsidian is restarted.

**Comment by joethei** [comment]
Are you talking about the articles not showing up on desktop, or are you using a separate synced device where they don't show up?

**Comment by frvkl** [comment]
This ticket concerns the desktop experience, but on mobile it does not seem to be working at all (see my comments on [#17 ](https://github.com/joethei/obsidian-rss/issues/17).

**Comment by joethei** [comment]
so when you run the refresh command on desktop, no new articles show up on desktop?
Have you checked this with a feed that you know has new entries?

**Comment by frvkl** [comment]
I did. I have the same rss feed in another RSS Reader installed on my phone. Multiple new articles were already available in the feed. After the Refresh command in Obsidian, the new articles did not show in the list. I then immediately restarted Obsidian and the new articles were showing in the list.

**Comment by joethei** [comment]
Does anything show up in the dev console(Cmd/Ctrl + Shift + I)?

**Comment by frvkl** [comment]
As far as I can see only a 403 for a feed favicon?

![image](https://user-images.githubusercontent.com/19724110/142737745-3b9c7346-554a-440c-a8ab-8802ad159767.png)

**Comment by joethei** [comment]
yeah, seams to be the only error, I am going to try fixing this tomorrow.
