### ISSUE TITLE
[FR] Subfolders in Filtered Folders

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#35]
I created a filtered folder for tagged articles as follows. However, this folder contains nothing, although I add tags for some feed articles. I have Obsidian v0.13.4 and Obsidian RSS 0.6.4 installed.
<img width="545" alt="Screenshot 2021-11-21 at 20 17 29" src="https://user-images.githubusercontent.com/44930227/142775969-170fc5ca-e14f-48dc-9e3a-df4f8b8f06f8.png">

**Comment by joethei** [comment]
do you have a tag named Tags?

**Comment by wenlzhang** [comment]
My bad. Didn't know that one should use the actual tag name in the field. 😅

**Comment by joethei** [comment]
No problem, there are a few things I need to make more clear in the settings.

**Comment by wenlzhang** [comment]
In this case, would it be possible to support creating sub-folders within filtered folders? For instance, one may have many tags, e.g. `Tag A` and `Tag B`. Then one can create separate folders for these, i.e. `Tag Folder A` and `Tag Folder B`. These folders are within the parent folder `Tagged`. This folder structure works in the same way as the folder structure when creating feeds.

**Comment by joethei** [comment]
yes, that is a good idea.
I have changed this issue to be the feature request for that.

**Comment by joethei** [comment]
the next update will include this functionality,
simply set the Filter name to `Folder/Subfolder`.
Only one layer of nesting is supported.
