### ISSUE TITLE
Support set default file name in the configuration pane

### ISSUE THREAD

**Issue by wenlzhang** [joethei/obsidian-rss#36]
Currently, one can default the file name to be the article title. It would also be useful if one can customize the file name to be something like `Title - 202111211200`. For this, one can set the file name as something like `{{title}} - {{date:YYYYMMDDHHMM}}` in the configuration pane.

**Comment by joethei** [comment]
with the next update you will be able to use the full power of templates in your note title.

**Comment by wenlzhang** [comment]
With the current version, one can use variables from the "paste template part". However, `{{created}}` is not part of such variables. Is it possible to include this variable?

Another thing is that one can configure the time stamp to be something like `YYYY-MM-DDTHH:MM` for use in the content of the note. In the title, however, a different date format may be desired. Therefore, is it possible to support using a different format in the title with something like `{{created:YYYYMMDDHHMM}}`?
