### ISSUE TITLE
Renaming the File Launched it?

### ISSUE THREAD

**Issue by eleanorkonik** [joethei/obsidian-rss#37]
I'm not totally sure why this happened, but when I tried to save a file off into my notes / "add as note" and then change the name it kept launching the link as I typed.

**Comment by joethei** [comment]
Does it Lauch when you type the letter O by any chance?

**Comment by joethei** [comment]
Okay, should be fixed with the update.
My implementation of #13 has been flawed.
@eleanorkonik
