### ISSUE TITLE
[Feature request] Tag autocompletion

### ISSUE THREAD

**Issue by annargrs** [joethei/obsidian-rss#38]
Tag autocompletion in the add-tags dialogue would be a fantastic way to avoid creating duplicate tags because of misspellings or simply not remembering the exact phrasing for an existing tag.

Also, maybe it's easier to just list them in the same field with a comma, like we do in the editor - rather than add them one-by-one?

**Comment by wenlzhang** [comment]
This feature would indeed be very useful!
