### ISSUE TITLE
[Feature Request] Add items to Folder from Links 

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#40]
Hello  @joethei !!!!!!

I'm having a great time importing my feeds to this fantastic plugin and I found a real workflow situation to share with you. 
- 95% of my feeds are from blogs posts which are web articles that I want to read and generate ideas/knowledge to connect to other sources of information from my vault 
- Ryan Holiday; James Clear; Mark Manson; Daily Stoic ...

There are some content that don't have a RSS Feed that I want to import to Obsidian. Three examples:

01 - Some unique/single links that someone shared with you that is a great article that you want to import to Obsidian but you think that you don't want to bring all RSS field from that site/creator.

02 - Some great sites don't have an RSS feed. My real world example is the site of the author of Atomic Habits - James Clear. 
- https://jamesclear.com/articles :(
- There are 200 links from this feed that I really want to import to Obsdian! 

03 - Some RSS Servers don't push all links from a feed: 
- From my feeds I realize that feeds from 3/4 years was not available in my RSS Server when comparing to what was available in the creator site.
- This way I need a way to manually insert this into the feed in Obsidian to have the complete content from that feed (future,present and past)

## My FR

A feature to manually add content to RSS Reader manually - `RSS Reader - Add items from a Link`

A modal to let the user paste links (more than one using `;` as a separator) to add items to Fodlers/Feeds 

### Modal Features
A- Accpet more than one link;
B- Add to a New Folder;
C- Add to a New Feed;
D - Add to an existing Folder; 
D1 - Add an existing folder + a new feed;
E- Add to an existing Feed (I don't know if it is feasible);
F - Add tags;

## Why I'm requesting 

It's so good to finally have a place to concentrate all my RSS feeds in Obsidian and creating notes with the same template and Organize them with all variables that we have that I really want to have a feature to add this complementary content to RSS Reader and everything with the same structure  

---

thank you very much !

Have a great day!

**Comment by joethei** [comment]
1. Importing entries from a feed, without adding the feed, can be done with an upcoming command:
![](https://i.joethei.space/RDNT2zXrV8.gif)

2. This is out of scope for this plugin as it involves parsing webpages.

3. currently implementing this by fetching old data from archive.org if a setting is enabled

**Comment by FelipeRearden** [comment]
> 1. Importing entries from a feed, without adding the feed, can be done with an upcoming command:

Woooowwww !!!!!!!! What a great idea @joethei :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: 

> 2. This is out of scope for this plugin as it involves parsing webpages.

100% understood :) Sorry for suggesting something that is not feasible this time :)


> 3. currently implementing this by fetching old data from archive.org if a setting is enabled

This is gonna  be amazing for me and would solve a big problem. Lookin g foward to see this in action :)


Thanks for the feedback !!!!

Have a great day!!!

**Comment by joethei** [comment]
With the next version you will be able to import entries from archive.org with a button in the settings.

Please keep in mind that only content which has been saved by archive.org will be imported.

**Comment by FelipeRearden** [comment]
> With the next version you will be able to import entries from archive.org with a button in the settings.

Great @joethei !!!! 

> Please keep in mind that only content which has been saved by archive.org will be imported.

Okay !!!!!!
