### ISSUE TITLE
[Feature Request] `New Feeds` ability to add Tags

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#41]
Hello @joethei !!!!!!!!

This FR is simple to explain: when adding a new feed to Obsidian RSS would be amazing to have a feature to add `tags` to all links from this feed. Would be a time saver to have all links to a feed with tags!

If possible, all new items from this feed will "born" with the tags too :)

My idea is to use this tags to create Filtered Lists combining items form different Folders and Feeds !

---

Thanks for reading this!

Have a great day!

**Comment by joethei** [comment]
With the next update you will be able to add tags to all entries by right clicking a folder(only normal, no filtered)

> My idea is to use this tags to create Filtered Lists combining items form different Folders and Feeds !

I guess this usecase is redundant with the update to filtered folders #28

**Comment by FelipeRearden** [comment]
> With the next update you will be able to add tags to all entries by right clicking a folder(only normal, no filtered)

Great idea @joethei !!! Thank you very much !!!!!

> I guess this usecase is redundant with the update to filtered folders #28

100% agree. This is much better then my FR !!!!!

Have a great day!

**Comment by FelipeRearden** [comment]
Working perfect on version `0.9.1` Obsidian `0.12.19` 

Thank you !!!!!!
