### ISSUE TITLE
Can we push the RSS icon into the sidebar, instead of a pane?

### ISSUE THREAD

**Issue by shivenigma** [joethei/obsidian-rss#46]
I tried to use the plugin in mobile but couldn't find the pane in the place I have in desktop. I think placing the RSS icon that opens the feed in the sidebar might make it usable on mobile as well.

or am I just a noob who can't figure out how to make this work on mobile?

**Comment by shivenigma** [comment]
Thanks for your excellent work on the plugin. I had this in my list but never got around doing it. This plugin works great for me.

**Comment by joethei** [comment]
If the view does not show up on the right side you might need to run the `RSS Reader: Open` command from the command pallete.

**Comment by shivenigma** [comment]
ok. I'll close this in that case.
