### ISSUE TITLE
[Help Request] CSS to Full Screen Mode

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#51]
Hello @joethei !!!!

Question is about an option to visualize the spectacular link view in Full Screen !

I tried to do this with CSS (Im not an expert I just do by try and error) and I got this

Before
![2](https://user-images.githubusercontent.com/85180696/146542925-3516610c-4502-4ae5-89f6-33be6237d381.png)

After
![1](https://user-images.githubusercontent.com/85180696/146542977-37995fb5-15d2-4bfd-9c4f-37aa4d8f3f8b.png)

But when I change the .modal, it breaks other windows of Obsidian that uses the same modal (I dont know the exact term to describe this) 

If you could help me with the right CSS targets, would be amazing :)

I'm feeling so good reading my RSS articles with your plugin  that a Full Screen window would be amazing for my workflow! 

Have a great day!

**Comment by joethei** [comment]
Seems like you found the one element that does not have a custom class assigned yet.
With the next update, this snippet will have the desired effect.
```
.rss-modal {
   width: 100%;
   height: 100%;
}
.rss-scrollable-content {
   height: 100%
}
```

**Comment by FelipeRearden** [comment]
You are fantastic @joethei !!!!!!!!!!!!!

**Comment by FelipeRearden** [comment]
Hello @joethei !!!!!!

Working perfect !!!!!!!

This is my snippet if anyone wants to try :)

```
.rss-modal {
	max-width: 100%;
	height: 100%;
	padding: 0px 15px 5px 20px;
}

.rss-scrollable-content {
   height: 80% !important;
}
```

Thank you very much for your help!!!!!

Have a great day!!!!!
