### ISSUE TITLE
All feeds gone & error message about date format

### ISSUE THREAD

**Issue by Y-a-n-i-n-a** [joethei/obsidian-rss#52]
Hi, I have updated to 0.9.1, and I don't see any of my feeds anymore, plus I get an error message from RSS reader plugin saying to check my settings, and that MM is not a correct format for minutes (rather mm). Changing format to correct & removing time altogether (ie. to YYYY-MM-DD) doesn't help.

I have restarted Obsidian, no go.

I understand the plugin is only at v 0.9, and I'll re-add the feeds if there's no solution, but I would appreciate if there is a simpler way to recover my feeds & way to manually back up before upcoming upgrades. Thank you

**Comment by joethei** [comment]
The message for the date format is static, so it will appear no matter what.

Could you check if your data is still in
`your vault/.obsidian/plugins/rss-reader/data.json`.
If so, you need to make sure the file content is valid JSON.
You can then fix any errors in that files while obsidian is not running.

**Comment by Y-a-n-i-n-a** [comment]
Hi, I have several backups with what I presume to be correct feeds, but if I copy them back, the feeds don't get restored. The plugin goes back to 0.6 version. Could you explain how to fix the errors? Sorry, I am not very IT proficient. 
Today I have updated Obsidian, and I'm getting the error message about wrong format again. I made a screenshot: https://imgur.com/a/1IAqVBm

**Comment by joethei** [comment]
The error message is static and has nothing to do with what your settings are,
it is just a reminder for those that might have changed their setting with the  wrong assumption about the format.
The message no longer shows up in the latest update(v0.9.2).

You only need to get the old `data.json`, the plugin handles all migrations that might be necessary.

You can check  if the `data.json` is valid by pasting its contents into a page like https://jsonlint.com/, the page should give you hints as to what is wrong.
(You can also upload it here for me to take a look, if you don't mind the content being shared)

Please make sure obsidian is **not** running while fixing those errors, as the plugin might just overwrite the file.

**Comment by Y-a-n-i-n-a** [comment]
You are very patient. Thank you, noted about the message.
I opened the data.json from the backups I have, and they don't have the feeds. Probably the feeds were gone earlier than I thought. But that's OK, because I think I got my answer. I can back up the feeds and restore them via this data.json file. 

Is that correct?

**Comment by joethei** [comment]
> Is that correct?

Yes the data.json contains all settings, as well as the articles and their status(read/unread...).

Make sure obsidian is closed when doing anything with that file manually, or the data might be overwritten.

**Comment by Y-a-n-i-n-a** [comment]
Noted. Thank you again for your support & for the plugin. I am a researcher, to have RSS feeds directly in Obsidian is really valuable.
