### ISSUE TITLE
Error Message "RSS Reader: Please check your settings, the default value for date format had an error, the correct format for minutes is mm not MM"

### ISSUE THREAD

**Issue by santiyounger** [joethei/obsidian-rss#55]
Hey, excited to use this plugin, however I had this issue that I don't know where to solve.

Upon installing the plugin I get this message:

![Pasted image 20211220105222](https://user-images.githubusercontent.com/51902730/146796071-9ff0d5f8-06a0-4f99-a0eb-3a193384b5fb.png)

>  "RSS Reader: Please check your settings, the default value for date format had an error, the correct format for minutes is mm not MM"

however I don't know what setting is asking me to change and where to change that, can you point me in the right direction on how to solve this?

Thank you

**Comment by joethei** [comment]
Hey,
In versions prior to 0.9.1, the default value for `Date format` has been `YYYY-MM-DDTHH:MM:SS`(so year-month-T-hour-month-second)
which is wrong and should have been `YYYY-MM-DDTHH:mm:SS`

This message is static and is there to notify old users that they might need to check
that their settings are correct
(as some might have assumed the syntax for minutes is `MM` and I can't check if a change has been made with wrong assumptions).

The message is not based on any of the settings you have set yourself.
As a result it might have shown up, even if your settings are correct.

The message will be removed in the next update, once enough users had the chance to see this.

**Comment by santiyounger** [comment]
got you, thanks that clears it up, I'll ignore the message then, thank you!
