### ISSUE TITLE
[Idea] Highlight in Reading View

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#60]
Hello @joethei !!!!!!!!!!

First of all, I know that is a crazy idea but if I don´t share this with you I couldnt sleep today :)

Since we can select text in the reading view my instinct is to have the ability to highlight the selected text 

## My FR
A button in the reading view (and a hotkey shortcut) to apply highlight to the selected text

### A. Create a New Note  Behavior

When creating a note, the note is created with the highlight text using Obsidian syntax `==selected_text==`

### B. New Variable `{{highlights:separator}}`

A new variable to gather all highlights. 

In my mind, the best separator is new lines `\n` . 

In my specific case I would use `{{highlights:\n\n}}` because I like to have a blank line between each highlight.

---

I dont know if is feasible and feel absolutely free to discard this. But I know that if this is feasible, you are one of the few people in this community that can make this happen. 

what you have been doing in all of your plugins in FANTASTIC! !!! :)

Thanks for reading this !

I wish you a fantastic day!

**Comment by joethei** [comment]
![](https://i.joethei.space/d8zrJUIe7W.gif)

Not working all the time currently, still some polishing to do.

**Comment by FelipeRearden** [comment]
You are a legend @joethei !!!!!!!!

I can't believe that is happening !!!!!!!!!!!

Thank you very much for making this real !!!!!!!!!!

AMAZING !!!!!!!

**Comment by wenlzhang** [comment]
This is also what I was looking for! It would be excellent for reading and annotating private stuff and replacing the Inoreader and Readwise combination for some cases.

Not sure if it is possible, but it would be great if the following can be achieved:

1. One highlights some text in the article reading window/view.
2. One extracts all highlights.
3. A note (`Note A`), e.g. `Annotation.md`, containing all highlights would be created.
    1. Also, a note (`Note B`), e.g. `Article.md`, containing the original article content would be created.
    2. Each highlight in `Note A` would have a block link to the original context in `Note B`.

For instance, `Note A` and `Note B` can be as follows:
```
# Note B

This is ==a sentence in note B==. ^blockid

```
```
# Note A

> a sentence in note B

- [[Note B#^blockid]]

```

In short, the workflow above would help link the extracted highlights to their original context that can be very useful for future revisit. Of course, there can be a separate command for choosing whether to save/link to the original article content together with the highlights.

The highlighted part in `Note B` does not need to have the highlight symbols `==a sentence in note B==`, if it is difficult to implement. It is the block link that matters more.

It would be great if the following can also be somewhat supported:

- One can customize the template for creating the annotation file, i.e. `Note A`. For instance,
    - Variables for creating `Note B` can be used.
    - There can be some new variables for denoting highlights, e.g. in the following example.
- One can unselect the highlighted text before creating the annotation file.

```
---
title: {{title}}
source: {{link}}

tags: [{{tags}}]

published at: {{published}}
created at: {{created}}
---

# {{title}}

> {{description}}

---

> {{highlight.text}}

- {{highlight.blockid}}

```

**Comment by joethei** [comment]
You will be able to create highlights in the next update.

@wenlzhang 
I have moved your request to #65, not sure how to even implement that though.

**Comment by FelipeRearden** [comment]
> You will be able to create highlights in the next update.

Thank you very much @joethei !!!!!!!!!

What a great news to start 2022 :) :) :)

**Comment by joethei** [comment]
you could just use
 ```
{{highlights:%%highlight%%
}}
```
for 1.
and 
 ```
{{highlights:%%highlight%%

}}
```
for 2. as your template.

`%%highlight%%` is one highlight in this case and the template gets processed for each.
Note the linebreaks as `\n` sadly does not work in this context.

**Comment by FelipeRearden** [comment]
AMAZING!!!!!

It worked @joethei !!!!!

Now I can customize the variable the way that I want !!!! 

Thank you very much for this trick !!!!

This is great 😊 

Have a great day!!!
