### ISSUE TITLE
DD-MM-YY HH:mm:ss throws error

### ISSUE THREAD

**Issue by johans3** [joethei/obsidian-rss#61]
I am no American so I use the European time format, and that is and will always be `DD-MM-YY HH:mm:ss`

Unfortunately, **RSS Obsidian** throws an error after each launch, saying MM must be mm.
I know the definition between months and  minutes

Finally I removed hours, minutes and seconds. 

Still, RSS Obsidian continues warning me, because `DD-MM-YY` isn't allowed. 
That's bitter because `YY-MM-DD` isn't universal nor my date /time format

**Comment by joethei** [comment]
That message you are seeing is not an error, just a notification for old users, see #55 for more information.
The message is shown to all users of v0.9.0 and v0.9.1 and has been removed in v0.9.2.
