### ISSUE TITLE
No longer working on Obsidian Mobile (IOS)

### ISSUE THREAD

**Issue by frvkl** [joethei/obsidian-rss#62]
When clicking to open on an article on Obsidian Mobile on IOS, it crashes and forces a reload of the Obsidian app. I was really into your plugin, but this is a deal breaker. 

I hope you are able to reproduce and fix the issue.

**Comment by joethei** [comment]
which version of the plugin are you running?

**Comment by frvkl** [comment]
![image](https://user-images.githubusercontent.com/19724110/147414328-dc32ccdb-c37a-4a28-9344-328495743c27.jpeg)

**Comment by joethei** [comment]
Okay, seems like I fixed it.
Could you check if the update also fixed the issue for you?

**Comment by frvkl** [comment]
It seems to be working again. Thank you for the quick solution 👍.
