### ISSUE TITLE
Filters are not working for Folders/Feeds

### ISSUE THREAD

**Issue by frvkl** [joethei/obsidian-rss#63]
Installed version plugin: 0.9.3
Version Obsidian: v0.13.14

I am trying to create filtered folders for 'unread' articles, from 'feeds' in a specific 'folder', but unread articles are not shown in the result list.

Was this working before?

**Comment by joethei** [comment]
What does your filter look like?

**Comment by joethei** [comment]
after some tests is can confirm this bug, the fix will be included in the next release.
