### ISSUE TITLE
Feed content not showing anymore on IOS

### ISSUE THREAD

**Issue by frvkl** [joethei/obsidian-rss#73]
Obsidian IOS v1.0.5
Plugin v1.0.4

After updating the plugin to v1.0.4, the content of an article is no longer visible on my Iphone.

![D582CA9C-483F-4C66-9227-765B22189CD8](https://user-images.githubusercontent.com/19724110/149665909-f8109424-33e8-4537-84ca-3da79f6d0cc2.png)

**Comment by joethei** [comment]
Please check if the issue has been fixed with v.1.0.5.
Seems like the fix for #70 is not fully compatible across devices.

**Comment by frvkl** [comment]
I can confirm that in version 1.0.5 the content is rendering again on iOS. 

Thanks for the quick fix 👍.
