### ISSUE TITLE
Broken RSS/Paste Content into Reader

### ISSUE THREAD

**Issue by base-I** [joethei/obsidian-rss#78]
Hi,

I just started playing around with the reader. I have one problem though: The Economist RSS Feeds do not seem to work.

https://www.economist.com/rss [I assume this is a matter of paywall :(]

I don't know why this is, but would it be possible to just paste the content (I have access to the economist) into the reader. That way I could at least use the functionality of the reader. 

Cheers

**Comment by joethei** [comment]
The feeds being empty of content is more of an issue with the feed only containing links,
you can generate long form using a service such as https://morss.it/

What would the usecase be for pasting content into a feed?<
This seems out of scope for this plugin.

**Comment by base-I** [comment]
Thanks! I will try it. 

Well the pasting content into it would be a workaround for using the interface when the rss does not work (which might not be relevant anymore)

**Comment by base-I** [comment]
morss.it helped. Thank you for the quick response :)
