### ISSUE TITLE
Empty rss content for wallabag feed

### ISSUE THREAD

**Issue by aschilling** [joethei/obsidian-rss#79]
Hi,

thank you for your work, this is a great plugin for obsidian. Unfortunately, the plugin does not work in combination with my self-hosted Read-Later service [wallabag](https://github.com/wallabag/wallabag). The feed is parsed and headlines are extracted appropriatly, but all items do not have a content. Although they have a content in the feed. I am sorry that I cannot give you a more precise error description, but the develpoper console does not show any errors. Do I have to look for parsing errors somewhere else?
The only way for you to reproduce the error would be to start wallabag in a docker image. I know this is can be a threshold for many developers, so if you DM me I give you a link to my private rss feed. Alternatively I am happy to assist you in the error debugging.

Best 
Andy

**Comment by joethei** [comment]
This is a strange one, because the feed looks completely correct, but will not get parsed.

**Comment by aschilling** [comment]
Thank you for your work. Do you think it could be an encoding issue? When I look at the wallabag feed, there are some non-utf-8 characters in it. Is this also the case in your wallabag feed?

**Comment by aschilling** [comment]
Thank you for your great work, most wallabag articles are now fetched correctly. However, there are still some articles without content, i.e. [https://www.platformer.news/p/why-social-networks-wont-stop-pushing](https://www.platformer.news/p/why-social-networks-wont-stop-pushing).
Is it possible that the closing body tag (</body>) within the content item creates a problem as there is no opening tag for the body tag? Can you reconstruct the issue?
