### ISSUE TITLE
[Idea] {{highlights}} with blockref using Carry-Forward Plugin Engine

### ISSUE THREAD

**Issue by FelipeRearden** [joethei/obsidian-rss#82]
Hello @joethei !!!!1

This idea is related to an expansion of the amazing features of RSS Reader -> Highlight in Reading View and the `{{highlights}}` 

1-  Add blockref to each line that has highlighted content `^blockid`;
2- when using the {{highlight}} variable, add the [[backlink]] syntax to connect `[[filename#^blockref]]` to the ==highlight== content

There is a plugin Called **Carry-Forward** that do exactly this: one of the commands sends to clipboard this syntax 
`{{selection}}[[filename#^blockref|alias]]` where:

- `selection` is the text selected by the user (if nothing is selected, it will use the whole line)
- `Alias` is a standard text defined by the user in the settings pane of the plugin; 

BUT the most important thing is that Carry-Forward supports **MULTIPLE CURSORS**. Take a look at the images below:

![0](https://user-images.githubusercontent.com/85180696/151858623-bc71eac3-d645-434d-977e-0a5048cbd965.png)
![1](https://user-images.githubusercontent.com/85180696/151858668-7f4c9e01-dfdc-4858-9f35-ba0e9d7c6705.png)
![2](https://user-images.githubusercontent.com/85180696/151858685-4b34bc8f-b33f-4c73-9d45-db69e537f7bf.png)
![3](https://user-images.githubusercontent.com/85180696/151858700-68fbba45-db4c-4506-a363-5106131eb361.png)

I know this plugin and its features very well because I'm the one who request support for multiple cursors and who did the tests of this version. 
- Carry-Forward link -> https://github.com/jglev/obsidian-carry-forward
- Link for my FR -> https://github.com/jglev/obsidian-carry-forward/discussions/11

## My FR: Integration with RSS Reader 

My idea is to integrate RSS Reader with Carry-Forward to make possible to have `{{highlights}}` with backlinks. 

If the user have Carry-Forward installed/toggle=ON then the {{highlights}} will be created with backlinks and blockref in the lines with ==highlights==

I have no idea if my idea is feasible :( I'm assuming that you copy the content of `==highlight==` to insert inside `{{highlights}}` maybe this copy method could use Carry-Forward engine if the vault has Carry-Forward installed. 

--- 

Let me know what you think :)

This idea have some relation with #65 

Have a great day!

**Comment by joethei** [comment]
This is a hard one because the Carry-Forward plugin uses some editor only functionality that I cannot use for this purpose.

Since the end result is similar to #65 I am closing this issue.

**Comment by FelipeRearden** [comment]
> This is a hard one because the Carry-Forward plugin uses some editor only functionality that I cannot use for this purpose.

Thanks for trying @joethei . I was trying to make things easier:)

> Since the end result is similar to #65 I am closing this issue.

100% agree 

Have a great day!!!
