### ISSUE TITLE
Importing images from RSS feeds fail - ouput is "METADATA" with no image shown

### ISSUE THREAD

**Issue by Thensley365** [joethei/obsidian-rss#88]
![image](https://user-images.githubusercontent.com/99222196/155832484-61d737db-4485-4796-baf7-0ae95d75c2ad.png)

Attached is an example. Can this be configurable?

**Comment by Thensley365** [comment]
Also- thank you for making this plugin - very excited to use with video/audio feeds!

**Comment by joethei** [comment]
What is the feed you are using?
